# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.1
    hooks:
      - id: check-jsonschema
        name: Validate chrome extension manifest schema
        files: ^manifest\.json$
        args:
          ["--schemafile", "https://json.schemastore.org/chrome-manifest.json"]

  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: bunx prettier --check
        files: \.(js|css|html|json|md)$
        language: system
      - id: eslint
        name: ESLint
        entry: bunx eslint
        files: \.[jt]sx?$
        types: [file]
        language: system
      - id: test
        name: Run Unit Tests
        entry: bun test tests/parser.test.js
        language: system
        pass_filenames: false
        always_run: true
      - id: commitlint
        name: commitlint
        entry: bunx commitlint --edit
        language: system
        stages: [commit-msg]
